#! /bin/sh

repo_loc=$HOME/.local/src
url="$(xclip -o)"

if [ -z "$url" ]; then
    notify-send "Clone Repository" "No url found in clipboard"
elif [ "${url#*\ *}" != "$url"  ]; then
    notify-send "Clone Repository" "Not a valid url:\n$url"
else
    cd $repo_loc 
    ERROR=$(git clone $url 2>&1 >/dev/null)
    if [ -z "$ERROR" ]; then
        notify-send "Clone Repository" "Cloned succesfully"
    else
        notify-send "Clone Repository" "$(echo $ERROR)"
    fi
fi
