#! /bin/sh
USERNAME="ace966"

ISSUE_LIST=$(lab issue list) || exit 1

ISSUE=$(echo "$ISSUE_LIST" | sed 's/#//g' | tr -cd '[:alnum:]- \n' | tr '[:upper:]' '[:lower:]' | sed 's/\ /-/g' | rofi -i -p ISSUE -markup-rows -dmenu)

[ -n "$ISSUE" ] || (echo "No issue selected. Aborting..."; exit 0;)

ISSUE_NR=$(echo "$ISSUE" | awk 'BEGIN {FS = "-" } ; { print $1 }')
MR_TITLE=$(echo "$ISSUE_LIST" | grep "$ISSUE_NR" | sed 's/\#[0-9]*\ //g')

git checkout -b "$ISSUE"
git push -u origin "$ISSUE"

lab issue edit "$ISSUE_NR" -a "$USERNAME" || echo "Failed to set user"
lab mr create -s -m  "Draft: $MR_TITLE" -m "Closes #$ISSUE_NR" -a "$USERNAME"

