#!/bin/sh
LAYOUTDIR=~/.scripts/screenlayout

SIMPLE=$(echo "hdmi-left\nhdmi-top\nhdmi-right\nhdmi-bottom\n7.81a\ncustom" | rofi -i -p Display -markup-rows -dmenu)

case $SIMPLE in
	hdmi-left)
		xrandr --output DP-3 --auto --left-of eDP-1			
		i3-msg "workspace 1, move workspace to output DP-3"
		i3-msg "workspace 2, move workspace to output eDP-1"
		;;
	hdmi-top)
		xrandr --output DP-3 --auto --above eDP-1			
		i3-msg "workspace 1, move workspace to output DP-3"
		i3-msg "workspace 2, move workspace to output eDP-1"
		;;
	hdmi-right)
		xrandr --output DP-3 --auto --right-of eDP-1			
		i3-msg "workspace 2, move workspace to output DP-3"
		i3-msg "workspace 1, move workspace to output eDP-1"
		;;
	hdmi-bottom)
		xrandr --output DP-3 --auto --below eDP-1			
		i3-msg "workspace 2, move workspace to output DP-3"
		i3-msg "workspace 1, move workspace to output eDP-1"
		;;
	7.81a)
		xrandr --output DP-1-1 --auto --right-of eDP-1			
		xrandr --output DP-1-2 --auto --right-of DP-1-1			
		i3-msg "workspace 3, move workspace to output DP-1-2"
		i3-msg "workspace 2, move workspace to output DP-1-1"
		i3-msg "workspace 1, move workspace to output eDP-1"
		;;
	custom)
		CUSTOM=$(echo "$(find $LAYOUTDIR/* -printf "%f\n")\narandr\n" | dmenu)

		case $CUSTOM in
			arandr)
				arandr
				;;
			*)
				$LAYOUTDIR/$CUSTOM
				cp $LAYOUTDIR/$CUSTOM $HOME/.screenlayout
		esac
		;;
esac

# set background image if exists to prevent
# having no fullscreen
if [ -e "$HOME/.wallpaper" ] ; then
	feh --bg-scale $HOME/.wallpaper
fi

