#! /bin/bash

REPO_LOC=$HOME/.local/src
find "$REPO_LOC" -name ".git" | while read -r line; do
    echo "Processing repo '$line'"
    (
    cd "$line" || exit
    cd ..
    REMOTE_URL=$(git remote get-url origin)
    if [[ $REMOTE_URL == *"git.haw-hamburg.de"* ]]; then
              echo "Repository contains 'git.haw-hamburg.de'. Setting user and email"
              git config --local user.name "Henri Burau"
              git config --local user.email "henri.burau@haw-hamburg.de"
              git config --local user.signingkey  6CF82EF795F9040C
    fi
    )
done
