#! /bin/sh
ACTION=$(echo -n "Shutdown\nRestart\nLock" | rofi -i -p System -markup-rows -width 10 -lines 5  -dmenu)

case $ACTION in
	Shutdown)
		shutdown now
		;;
	Restart)
		systemctl reboot
		;;
	Lock)
		dm-tool lock
esac	
