#! /bin/sh
ACTION=$(echo "Shutdown\nRestart\nLock" | rofi -width 10 -lines 3 -p "System" -dmenu)

case $ACTION in
	Shutdown)
		shutdown now
		;;
	Restart)
		systemctl reboot
		;;
	Lock)
		lock 
		systemctl suspend
esac	
