#!/bin/sh
xrandr --output HDMI1 --mode 1920x1200 --pos 0x0 --rotate normal --output LVDS1 --primary --mode 1366x768 --pos 1920x432 --rotate normal --output VIRTUAL1 --off --output DP1 --off --output VGA1 --off
